---
title: "stats"
author: "Siming Yan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
 
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    # css: bootstrap.min.css
    theme:
      bslib: true
      version: 4
      bg: "#ff7f50"
      fg: "#191960"
      primary: "#ED79F9"
      navbar-bg: "#3ADAC6"
---

<style>
.colored {
  background-color: #FAFAFA;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F, include=F}
library(tidyverse)
library(lfe)
library(reshape2)
library(flexdashboard)
library(zoo)
library(corrplot)
 
getwd()
df <- read_csv('./df_final_97.csv')
 # df %>% View()
# names(df)
t = {}
for (i in names(df)){
  
  t = append(t , gsub('\\w+\\.', '', i))
}
names(df) = t
# df

df = df %>% drop_na()
# sum(df %>% is.na())
df$log_inb_qty = log(df$inbound_receive_qty)
df$log_oub_qty = log(df$outbound_shipped_qty)

df = df[is.na(df$log_inb_qty) != T & is.na(df$log_oub_qty) != T, ]
df = df[is.infinite(df$log_inb_qty) != T & is.infinite(df$log_oub_qty) != T, ]


# df$log_oub_qty %>% min()


df_cals = df %>% group_by(ou_code) %>% summarise(sd(log_inb_qty), 
                                         sd(log_oub_qty),
                                       mean(log_inb_qty),
                                       mean(log_oub_qty))
# df_cals
# ggplot(df) + aes(x=log_inb_qty) +
#   geom_histogram()
# ggplot(df) + aes(x=log_oub_qty) +
#   geom_histogram()

 
df = merge(df, df_cals, on = ou_code)
df %>% dim()
# df_backup = df
df = df[df$log_inb_qty < df$`mean(log_inb_qty)`+ 2*df$`sd(log_inb_qty)` & 
   df$log_inb_qty> df$`mean(log_inb_qty)`- 2*df$`sd(log_inb_qty)`, ]
df = df[df$log_oub_qty < df$`mean(log_oub_qty)`+ 2*df$`sd(log_oub_qty)` & 
   df$log_oub_qty > df$`mean(log_oub_qty)`- 2*df$`sd(log_oub_qty)`, ]

df %>% dim()
df$operation_day %>% unique()
```


```{r}

devtools::install_github(
  "https://github.com/fyenne/praise/releases/download/v1.0.2/praise_1.0.2.tar.gz",
  type = "source")

felm(total_working_hour ~ inbound_receive_qty + 0 |ou_code| 0|ou_code, data = df) %>%
  summary()
```

```{r}
lmer(total_working_hour ~ inbound_receive_qty + (1|ou_code)  , data = df)
```


```{r, include = F}
felm(total_working_hour~ inbound_receive_qty  , data = df[df$ou_code == 'CN-300', ]) %>% summary()

# 
# cor(df$total_working_hour, df$inbound_receive_qty,
#     df$outbound_shipped_qty)

cor_in = {}
for (i in unique(df$ou_code)){
  cor_in = cor_in %>% append(cor(
    df[df$ou_code == i, ]$total_working_hour, 
    df[df$ou_code == i, ]$inbound_receive_qty))
}

cor_out = {}
for (i in unique(df$ou_code)){
  cor_out = cor_out %>% append(cor(
    df[df$ou_code == i, ]$total_working_hour, 
    df[df$ou_code == i, ]$outbound_shipped_qty))
}


cor_sum = {}
for (i in unique(df$ou_code)){
  cor_sum = cor_sum %>% append(cor(
    df[df$ou_code == i, ]$total_working_hour, 
    (df[df$ou_code == i, ]$outbound_shipped_qty + 
       df[df$ou_code == i, ]$inbound_receive_qty)))
}

 


cor_df = data.frame(unique(df$ou_code), cor_in, cor_out, cor_sum) 
  # write.csv('./cor_data_out.csv', fileEncoding  = 'utf-8')

cor_check = function(code){
  c(cor(df[df$ou_code == code,]$total_working_hour,
      df[df$ou_code == code,]$inbound_receive_qty),
      cor(df[df$ou_code == code,]$total_working_hour,
      df[df$ou_code == code,]$outbound_shipped_qty),
    cor(df[df$ou_code == code,]$total_working_hour,
      (df[df$ou_code == code,]$outbound_shipped_qty + 
         df[df$ou_code == code,]$inbound_shipped_qty))) 
}


 
names(cor_df)[1] = 'ou_code'


cor_df = merge(df[,c("ou_code", "ou_name")] %>% distinct(),cor_df,on = "ou_code")


# 
# cor_df %>%
#   write.csv("./cor_df.csv",
#           row.names = F, fileEncoding = 'UTF-8')
df
df[, c("total_working_hour", "inbound_receive_qty", "outbound_shipped_qty")]

library(RColorBrewer)
cor(df[, c("total_working_hour", "inbound_receive_qty", "outbound_shipped_qty")]) %>%
  corrplot.mixed( lower = 'shade', upper = 'pie', order = 'hclust',
                  col = brewer.pal(n = 10, name = 'PRGn'))
  

```

```{r}
pltdf = pivot_longer(df[c('ou_code', 'inbound_receive_qty', 'outbound_shipped_qty', 'outsource_working_hour' )],
     cols  =  c('inbound_receive_qty', 'outbound_shipped_qty' ) )
pltdf = pltdf[pltdf$outsource_working_hour != 0, ]
# pltdf
ggplot(pltdf) + aes(x = value, y = outsource_working_hour, 
                    group = name,
                    color = name
                    ) + 
  geom_point() +geom_smooth()
```



```{r, include= FALSE}
# df$ou_name
big_10 = c("CN-256",
"CN-035",
"CN-067",
"CN-305",
"CN-242",
"CN-175",
"CN-051",
"CN-298",
"CN-406")
 
# cor_check("CN-300") 
cor_df = cor_df %>% melt

cor_df_10 = cor_df[cor_df$ou_code %in% big_10, ];cor_df_10

cor_df_10
# # corr square equals to regression R^2 when having intercept.
# cor_df
# inner_join(cor_df, df[,c("ou_code", "ou_name")], on = "ou_code")
# cor_df_10
# 
# df[df$ou_code == 'CN-242', ]
# df_backup[df_backup$ou_code =='CN-242',]
```

```{r, message = F, include= = F}
library(plotly)


# cor_df[cor_df$variable == 'cor_in', ]
fltr_in = mean(cor_df[cor_df$variable == 'cor_in', ]$value) +
   .5*sd(cor_df[cor_df$variable == 'cor_in', ]$value)

fltr_out = mean(cor_df[cor_df$variable == 'cor_out', ]$value) +
   .5*sd(cor_df[cor_df$variable == 'cor_out', ]$value)


fltr_sum = mean(cor_df[cor_df$variable == 'cor_sum', ]$value) +
   .5*sd(cor_df[cor_df$variable == 'cor_sum', ]$value)
# cor_df
p1 = ggplot(data = cor_df) + 
  aes(x = value, group = variable, fill = variable)+
  geom_histogram(position = 'dodge') + 
  geom_vline(aes(xintercept = fltr_in),
             color = 'red', linetype = 'dashed') +
  geom_vline(aes(xintercept = fltr_out ),
             color = 'darkgreen', linetype = 'dotdash') + 
  geom_vline(aes(xintercept = fltr_sum),
             color = 'darkblue', linetype = 'dash')

```

```{r, echo = F, message= F}
ggplotly(p1)
 
```

```{r}
cor_df_10[cor_df_10$variable == 'cor_in' & cor_df_10$value < fltr_in, ]

```

```{r}
cor_df_10[cor_df_10$variable == 'cor_out' & cor_df_10$value < fltr_out, ]
```


```{r}
cor_check("CN-035")
```


# ---------------------------------

---


```{r, echo = F}
felm(outsource_working_hour~ 
       inbound_receive_qty + outbound_shipped_qty, data = df[df$ou_code == 'CN-406', ]) %>% summary()
```




```{r, include = F}
# 
# cor(df$outsource_working_hour, df$inbound_receive_qty,
#     df$outbound_shipped_qty)

cor_in_os = {}
for (i in unique(df$ou_code)){
  cor_in_os = cor_in_os %>% append(cor(
    df[df$ou_code == i, ]$outsource_working_hour, 
    df[df$ou_code == i, ]$inbound_receive_qty))
}

cor_out_os = {}
for (i in unique(df$ou_code)){
  cor_out_os = cor_out_os %>% append(cor(
    df[df$ou_code == i, ]$outsource_working_hour, 
    df[df$ou_code == i, ]$outbound_shipped_qty))
}


cor_sum_os = {}
for (i in unique(df$ou_code)){
  cor_sum_os = cor_sum_os %>% append(cor(
    df[df$ou_code == i, ]$outsource_working_hour, 
    (df[df$ou_code == i, ]$outbound_shipped_qty + 
       df[df$ou_code == i, ]$inbound_receive_qty)))
}

 


cor_df_os = data.frame(unique(df$ou_code),
                       cor_in_os, cor_out_os, cor_sum_os) 
  # write.csv('./cor_data_out.csv', fileEncoding  = 'utf-8')
names(cor_df_os)[1] = "ou_code"
cor_df_os = cor_df_os %>% 
  merge(cor_df[c("ou_code", "ou_name")] %>% distinct(), 
        on = "ou_code")
# cor_df_os
cor_check_os = function(code){
  c(cor(df[df$ou_code == code,]$outsource_working_hour,
      df[df$ou_code == code,]$inbound_receive_qty),
      cor(df[df$ou_code == code,]$outsource_working_hour,
      df[df$ou_code == code,]$outbound_shipped_qty)) 
}
```


```{r, include= FALSE}
big_10 = c("CN-256",
"CN-035",
"CN-067",
"CN-305",
"CN-242",
"CN-175",
"CN-051",
"CN-298",
"CN-406")

# cor_check("CN-300") 
cor_df_os = cor_df_os %>% melt()
cor_df_os['value'][which(is.na(cor_df_os['value'])) , ] = 0
cor_df_os
 
cor_df_10_os = cor_df_os[cor_df_os$ou_code %in%
                           big_10, ]
# which(is.na(cor_df_10_os['value'])) 
cor_df_10_os
# corr square equals to regression R^2 when having intercept.
```

```{r, message = F, include= = F}
library(plotly)

cor_df_os = cor_df_os[cor_df_os$value != 0 , ]
# cor_df[cor_df$variable == 'cor_in', ]
in_os_mean =  mean(cor_df_os[cor_df_os$variable == 'cor_in_os', ]$value)+1*sd(cor_df_os[cor_df_os$variable == 'cor_in_os', ]$value)

out_os_mean = mean(cor_df_os[cor_df_os$variable == 'cor_out_os', ]$value)+1*sd(cor_df_os[cor_df_os$variable == 'cor_out_os', ]$value)
# out_os_mean

sum_os_mean = mean(cor_df_os[cor_df_os$variable == 'cor_sum_os', ]$value)+1*sd(cor_df_os[cor_df_os$variable == 'cor_sum_os', ]$value)

p1 = ggplot(data = cor_df_os) + 
  aes(x = value, group = variable, fill = variable)+
  geom_histogram(position = 'dodge') + 
  geom_vline(aes(xintercept = in_os_mean),  # in 
             color = 'red', linetype = 'dashed') + 
  geom_vline(aes(xintercept = out_os_mean ),  # out
             color = 'darkgreen', linetype = 'dotdash') + 
  geom_vline(aes(xintercept = sum_os_mean), # sum
             color = 'darkblue', linetype = 'dash')

```

```{r, echo = F, message= F}
ggplotly(p1)
 
```

```{r}
cor_df_10_os[cor_df_10_os$variable == 'cor_in_os' & cor_df_10_os$value < in_os_mean, ]

```

```{r}
cor_df_10_os [cor_df_10_os$variable == 'cor_out_os' & cor_df_10_os $value < out_os_mean, ]
```

```{r}
cor_df_10_os [cor_df_10_os$variable == 'cor_sum_os' & cor_df_10_os $value < sum_os_mean, ]
```